spring.application.name=course-service
server.port=8082
spring.data.mongodb.database=coursedb
spring.data.mongodb.uri=${COURSE_SERVICE_MONGODB_URI:${MONGODB_URI:mongodb://localhost:27017/coursedb}}
security.api-key=${SECURITY_API_KEY:${COURSE_SERVICE_API_KEY:course-service-secret-key-456}}

# OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

