spring.application.name=course-service
server.port=8082
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/coursedb}
security.api-key=${SECURITY_API_KEY:test-secret-key-123}
