spring.application.name=course-service
server.port=8082
spring.data.mongodb.database=coursedb
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/coursedb}
security.api-key=${COURSE_SERVICE_API_KEY:course-service-secret-key-456}
