spring.application.name=user-service
server.port=8081
spring.mongodb.uri=mongodb+srv://sachilz:HrXrhCOrRfE9go1U@cluster0.be9f7gl.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://sachilz:HrXrhCOrRfE9go1U@cluster0.be9f7gl.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0
security.api-key=test-secret-key-123